name: CI - Tests avec Bun.js

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Vérifier le code source
        uses: actions/checkout@v4

      - name: Configurer Bun.js
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Installer les dépendances
        run: bun install

      - name: Exécuter les tests
        run: bun test
