name: Test evift-api

# Déclenche le workflow à chaque push ou pull request sur main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/bun-action@v1
        with:
          bun-version: '1.1.12'

      - name: Install dependencies
        run: bun install

      - name: Apply migrations
        run: bun migrate

      - name: Run tests
        run: bun test
